dist: trusty
group: beta
language: node_js
node_js:
- lts/erbium
cache:
  directories:
  - node_modules
before_install:
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
- if [ -d node_modules ] && [ x$(cat node_modules/.last-node-version 2>/dev/null) != x$(node -e 'console.log(process.version)') ]; then npm rebuild --update-binary && node -e 'console.log(process.version)' > node_modules/.last-node-version; fi
before_script:
- npm run build
script:
- npm run lint
- npm test
deploy:
  skip_cleanup: true
  provider: npm
  email: npm@collaborne.com
  api_key:
    secure: "XqPAqtTDBBqxJq6KzzVbsBnBMRNx39DJ+BZvxwO0vXNHdE1P3ZgZb5Rs3hdWEo+qzdiqCbl9fLGD14WaekZ+ra3EbrUU/AIl98UZej7plsTFTmiksZty6UXaCc7/NBr7eJM2r4do+HDgxr/eBnTVtDXV23GV3HnEeO/v3UoOgAkfBxGqIrYNnZ4AeJMHVak6UHXf4b8YO06SJnCDGWNWKTTxnGbwfU/1oqeX2Z/n36/PZS3dCUL2/1EyrknHAgxJuMtkQTkJfKt76lpwCD5hq8K9ptmcnlpS/4Y5fLCJ9uM20wqay1AXWOgvBgivLezCzbj7PWTm10TRDS+69iID6cotyTJJM1ldaeBWrpmGjs+HXRRD73qYeodwA/d5bF/5G0GVIZzPoE7xkK0VEkMJy1mgCLOCngtUL79EYeaO7Cjh/YggqUfcrZ4RnyOl2NofvLYWLdhmY9jDz6NlF08tsFhJqezX+2bQ26rxQEApuE1cReEXzhVpYPKWZwuWw6DfrZXvkKYxO3I3imbqlIFWlkjGbtZ/BlOwTcNJ8JuDDrGg2dRH9BOli1nx66p3/d+DlE4d23nx/fAPgd9rssPaZ+BRyd58k8YqF8YQ+lDyTGvJhZk2zA1lCA1Lj3Dytfaeo7dekJCwjHCXO2ExTnuKEvUTAqIgj+7BKfGzgJttfrY="
  on:
    tags: true
    condition: $(node -e 'console.log("v" + require("./package.json").version)') = ${TRAVIS_TAG}
